configurationFiles:
  my.cnf: |-
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    log_bin=postdb.bin
    binlog_format=ROW
    server-id=1
mysqlDatabase: post_DB
mysqlRootPassword: password
# persistence:
#   existingClaim: post-db-pvc