# name: Generate SQL Document

# on:
#   push:
#     paths:
#     - 'db/sql/**'

# jobs:
#   gen-doc:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: create-network
#         run: make createnet

#       - name: gen-doc 
#         run: make sqldoc a=up

#       - name: Commit
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add db/
#           git commit -m "[Add] Generate SQL Document"
    
#       - name: Push to GitHub
#         run: git push